version: "3.2"

services:
  db:
    ports:
      - "5432:5432"
    image: postgres:16
    volumes:
      - accounting-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=accounting
      - POSTGRES_PASSWORD=unicorn
      - POSTGRES_DB=accounting
    restart: unless-stopped

volumes:
  accounting-db:
